version: 0.2
os: linux
files:
  - source: /home/ubuntu/flaskapplication/app
    destination: /home/ubuntu/flaskapplication/app
  - source: /home/ubuntu/flaskapplication/requirements.txt
    destination: /home/ubuntu/flaskapplication/
  - source: /home/ubuntu/flaskapplication/appspec.yml
    destination: /home/ubuntu/flaskapplication/
  - source: /home/ubuntu/flaskapplication/cert.pem
    destination: /home/ubuntu/flaskapplication/
  - source: /home/ubuntu/flaskapplication/key.pem
    destination: /home/ubuntu/flaskapplication/
  - source: /home/ubuntu/flaskapplication/scripts
    destination: /home/ubuntu/flaskapplication/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ubuntu
