#!/bin/bash

# Navigate to the FastAPI application directory
cd /home/ubuntu/flaskapplication/app

# Start the FastAPI application using uvicorn
uvicorn app:app --host 0.0.0.0 --port 5000 --ssl-keyfile key.pem --ssl-certfile cert.pem
